### ISSUE TITLE
Inconsistent results with larger IDs

### ISSUE THREAD

**Issue by dig412** [olivere/esdiff#2]
We've been using esdiff quite a bit and have found it sometimes returns inconsistent results - that is running it multiple times against the same two indexes will produce different results.
It also seems to be missing some new documents entirely.

I've come up with the following test case:
```sh
#!/bin/sh
curl -H 'Content-Type: application/json' -XDELETE 'localhost:19201/oldindex'
curl -H 'Content-Type: application/json' -XDELETE 'localhost:19201/newindex'
curl -H 'Content-Type: application/json' -XPUT 'localhost:19201/oldindex/event/239473748' -d '{"id":"239473748","name":"Same Document"}'

curl -H 'Content-Type: application/json' -XPUT 'localhost:19201/newindex/event/239473748' -d '{"id":"239473748","name":"Same Document"}'
curl -H 'Content-Type: application/json' -XPUT 'localhost:19201/newindex/event/34' -d '{"id":"34","name":"New Document"}'
curl -H 'Content-Type: application/json' -XPUT 'localhost:19201/newindex/event/32' -d '{"id":"32","name":"New Document 2"}'
```

This runs against two indexes on ES6, but I discovered the behaviour on ES5.
I then run the following command repeatedly:
```
esdiff -a=true -c=true -d=true -u=true http://localhost:19201/oldindex/event http://localhost:19201/newindex/event
```

And get mostly:
```
Unchanged       239473748
```
Sometimes:
```
```
Rarely:
```
Unchanged       239473748
Created 32      {*diff.Document}:
        -: (*diff.Document)(nil)
        +: &diff.Document{ID: "32", Source: map[string]interface {}{"id": "32", "name": "New Document 2"}}
```

I think this is something to do with the id field - if I use only small numbers it works fine, if some of the documents have larger IDs the problem starts.

Please let me know if you need any more information.

**Comment by olivere** [comment]
Oh, that really looks like a bug. Thanks for reporting.

I think there was a subtle edge-case in the differ I fixed in a "special version" of esdiff for Bodleian Library in the UK in [this commit](https://github.com/olivere/bodleiandiff/commit/d8b0608062d9fc980942e234f997e8b0fc402946). If you have the time to confirm if the two changes [here](https://github.com/olivere/bodleiandiff/commit/d8b0608062d9fc980942e234f997e8b0fc402946#diff-cf142fdd50aee3b70311e9a087fc01acR183) and [here](https://github.com/olivere/bodleiandiff/commit/d8b0608062d9fc980942e234f997e8b0fc402946#diff-cf142fdd50aee3b70311e9a087fc01acR206) would fix the issue, I'd be happy to merge it. Otherwise, I'll have a look at it for the next version.

**Comment by dig412** [comment]
Thanks for the quick reply - I'm afraid that change doesn't fix it. 

Some more information - if I change the order of the test documents to this:
```
#!/bin/sh
curl -H 'Content-Type: application/json' -XDELETE '192.168.99.100:19201/oldindex'
curl -H 'Content-Type: application/json' -XDELETE '192.168.99.100:19201/newindex'
curl -H 'Content-Type: application/json' -XPUT '192.168.99.100:19201/oldindex/event/3' -d '{"id":"1","name":"Same Document"}'

curl -H 'Content-Type: application/json' -XPUT '192.168.99.100:19201/newindex/event/3' -d '{"id":"1","name":"Same Document"}'
curl -H 'Content-Type: application/json' -XPUT '192.168.99.100:19201/newindex/event/2' -d '{"id":"2","name":"New Document"}'
curl -H 'Content-Type: application/json' -XPUT '192.168.99.100:19201/newindex/event/1' -d '{"id":"3","name":"New Document 2"}'
```

That is the unchanged document comes last instead of first, the results are correct. I have also managed to make it break with small IDs, so perhaps it's related to ordering.

**Comment by olivere** [comment]
Reproducible test cases are pure gold, so thanks for that. I will look at it.

If you want to dig deeper, you can enable trace logging and log the actual output between `esdiff` and Elasticsearch by passing a `tracelog=<filename>` in the URL (see [here for an example](https://github.com/olivere/esdiff/blob/master/elastic/config/config.go#L29)).

**Comment by olivere** [comment]
I think I found an issue with a misuse of goroutines. Can you try again?

Notice that I also added a feature to control sorting now with e.g. `-ssort=id.keyword` and `-dsort=id.keyword`. By default, sorting is now by `_doc` [1].

[1] https://www.elastic.co/guide/en/elasticsearch/reference/5.6/search-request-scroll.html

**Comment by dig412** [comment]
I've tested the new version and everything seems good.
I was a bit worried about the `_doc` sorting change when you committed it - I was sure the algorithm depended on documents arriving in a consistent order, so I'm glad i hadn't misunderstood.

All the included tests pass on my machine, and I've also subjected it to a stress test - an index of 20,000 random documents, with 1500 additions, 1500 deletions, and 1500 changes. It passed with flying colours - every different document was detected properly!

Thanks very much for fixing this!
